//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_orders
    {
        public int id { get; set; }
        public string orderNum { get; set; }
        public Nullable<int> userId { get; set; }
        public string userName { get; set; }
        public string contactPerson { get; set; }
        public string contactMobile { get; set; }
        public string contactTel { get; set; }
        public string contactEmail { get; set; }
        public Nullable<decimal> expendTotal { get; set; }
        public Nullable<decimal> expendFirst { get; set; }
        public Nullable<System.DateTime> expendTime { get; set; }
        public Nullable<System.DateTime> expendPaymentTime { get; set; }
        public Nullable<decimal> incomeTotal { get; set; }
        public Nullable<decimal> incomeFirst { get; set; }
        public Nullable<System.DateTime> incomeTime { get; set; }
        public Nullable<System.DateTime> incomePaymentTime { get; set; }
        public Nullable<decimal> advanceSpend { get; set; }
        public Nullable<decimal> roomCount { get; set; }
        public Nullable<decimal> refundRoomCount { get; set; }
        public Nullable<int> isOnline { get; set; }
        public Nullable<int> isChujia { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> orderStatus { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public string remark { get; set; }
        public Nullable<int> isInvoice { get; set; }
        public string hotelid { get; set; }
        public Nullable<int> isTravelOrder { get; set; }
        public Nullable<System.DateTime> travelOrderTime { get; set; }
        public string travelOrderAdmin { get; set; }
        public string noLineOrderAdmin { get; set; }
        public string remarkCustomer { get; set; }
        public string remarkTravel { get; set; }
        public string remarkAdmin { get; set; }
        public Nullable<decimal> canOpenInvoiceAmount { get; set; }
        public Nullable<int> payor { get; set; }
        public Nullable<decimal> incomePostMoney { get; set; }
        public Nullable<decimal> outputPostMoney { get; set; }
        public Nullable<System.DateTime> expendInvoiceTime { get; set; }
        public string orderOpreatorAdmin { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public Nullable<int> activityType { get; set; }
        public Nullable<int> isEnabled { get; set; }
        public Nullable<System.DateTime> planningcommissionTime { get; set; }
        public Nullable<System.DateTime> salescommissionTime { get; set; }
        public Nullable<int> businessSource { get; set; }
        public string salePerson { get; set; }
        public Nullable<decimal> expendRefund { get; set; }
        public Nullable<decimal> expendRefunded { get; set; }
        public Nullable<decimal> incomeRefund { get; set; }
        public Nullable<decimal> incomeRefunded { get; set; }
        public Nullable<int> jielvstatus { get; set; }
        public string jielvClause { get; set; }
        public string hotelName { get; set; }
        public Nullable<int> isComment { get; set; }
        public Nullable<int> orderPaytype { get; set; }
        public Nullable<int> delDegree { get; set; }
    }
}
